CREATE TABLE book(
id LONG AUTO_INCREMENT,
title VARCHAR(255) NOT NULL,
author_id LONG NOT NULL,
`year` INT NOT NULL,
genre VARCHAR(255) NOT NULL
);
CREATE TABLE author(
id LONG AUTO_INCREMENT,
name VARCHAR(55) NOT NULL,
birth_year INT
);